"""one vote per user and poll

Revision ID: c49a504a6999
Revises: 0810e36df54b
Create Date: 2026-10-05 13:41:40.628361
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c49a504a6999"
down_revision: str | None = "0810e36df54b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 1. Add poll_id as nullable, backfill it from the option, then make it mandatory.
    #    Existing votes are kept; the autogenerated NOT NULL column would fail on them.
    op.add_column("votes", sa.Column("poll_id", sa.Uuid(), nullable=True))
    op.execute(
        "UPDATE votes SET poll_id = options.poll_id FROM options WHERE options.id = votes.option_id"
    )
    op.alter_column("votes", "poll_id", nullable=False)
    op.create_foreign_key(
        op.f("fk_votes_poll_id_polls"), "votes", "polls", ["poll_id"], ["id"], ondelete="CASCADE"
    )

    # 2. Votes cast before accounts existed have no voter (NULLs never collide in a
    #    unique constraint), every new vote is tied to a user.
    op.add_column("votes", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_votes_user_id_users"), "votes", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    op.create_unique_constraint(op.f("uq_votes_poll_id_user_id"), "votes", ["poll_id", "user_id"])


def downgrade() -> None:
    op.drop_constraint(op.f("fk_votes_poll_id_polls"), "votes", type_="foreignkey")
    op.drop_constraint(op.f("fk_votes_user_id_users"), "votes", type_="foreignkey")
    op.drop_constraint(op.f("uq_votes_poll_id_user_id"), "votes", type_="unique")
    op.drop_column("votes", "user_id")
    op.drop_column("votes", "poll_id")
