---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: votely-db
  namespace: votely-prod
spec:
  encryptedData:
    database: AgB6brNxxZAYkoM0Wt/T9Ovl6MAuLf1UUf2+gNA4qdblQ2+IbTRe/+O2KG/9WpB2R3x97SNGymar3pLsvbykaJFvLgipkYKcJrIFyXQLrHUbpbB5cnCJEm04Hf7PYnjAJbhLSvAmaX4eLA6OS93da9l+b/R3aOLl5bNMsUc6TYQV0/WkxEP5H+ticrCH36Z4T+jBC0nC2HJj4o7mOkeSsIb41mWfCQfzb53+tDJS93VDZTMur+AwL7V01NWJbPHxMIGi3m/qsJM+nhpLePeuwckHjrN9Q8gZ5uBdkD+42q2F8dOezNLDnYYpgbxiUsTy/nd7i8F0OfT84RpgzqQLUJ2hRFMiQvhE1zkM++bgpJv28bqWiKOqI9Gqg3ufVuX0aRYdwQug4pdbnSTQDAh5qJMxEwmYIPTlzwRYkvsTgF+8p+Mz7kxHRulQvw7RdRKoqS6OCZzlcVe1b7bjD5tNEpup33zbpwhY4XCjIbps29Mfc7Rh0uFSoqt5ftmV9DGxuY5dXorRkm8Xce7teSI5qF+nHtyNCpGStkLcZxF2DnjWciXszmhcaqTegxwMFrW7396v+89N/jjfsSzm+u966ppwwXPilzNlsJP6IKH0gumts7UXlTLrfbxAP/MfQLZUqMlfkiLs4pleE3j51A7Z1c0QpL41gmaJ4MDpS1zqi0KFBY6lU0NXKkRjuHHzK351DyE6APGseMg=
    password: AgBhoHIDCthZtkWydMV435ivs3POqPjX3MhFrb4LH+hx8293Yx1zj/H6jemo3GXkq7+a+TRkAYSIrzxQDgmr6jwKVk4w6WIVgGq57zBVKtn0kzd2scwUmRerlvpmk0Qg4a4slEpQpJF/YvzX8v5JKY1P2gKiQZQMBU1uFw34vsJ+buIB0crYfDJh7v3Q6tg2j9ermRjzPdEj/RMcP8aCwdXB/YEyjx5aATxU675E2N+XqqcAp/F3ZG6luZD9JsS5OLeY2k4WrZoWFSlPmJrJR5n9exfCcw2CNWQfmWAFxZyKqfRKLfCQq24vOPFD2JPRQTt3AJx+OH99kh0/tK87XHi5LAregXwBAdiPkmyEo0mOQRPubyOMG9VeIZNKJ01rY0ViNO5zXfli5hEgsVjRfjgl94au786PQ796jmM7JYr6uqMvTaDB6GaUNYTli+5DXkkNdpYXHITCsuKsWXXpmgwc4Zi+t5Nj2/R21ToHVD7SlDEiOnFcPZvAVYT6OdPYVMa1/RzRuMm/sdnJwfqxskQcV4OMdSNxc4N5zSJYKnm2/tscKXfMpCXoLQNvRY7iMxekbzey1pQCsLvYm0GuSOiyyIw1SU4vqRme3XQD2r9ZxXLqcY+iU6Il1Aw5wRP4LyFs3RhWK9kknWJci7nW2qWxMA6qinhaDUZhFdhn9T81SDFHf9nmBxlfX/KdVtp4203MOrA79ItzMUhyU2Nhq9lmwX1vbjW/4//7Xg3nP7Kf2wvIhHdJ4TdCbb83QeqyLvU=
    username: AgDIZ8QUhIxy4SMZH9UQbA5PaD7C+whVctYZ18dMpfIEd8qcZcjP4sCPPGb+1v6jxEcQ1WnX2GTRhhe9UWbSCV9ad7obn+jSp5ngH9c3Ssjl6IuqCt8BON2zUg5ckWF+Re0JHdf42em+PDsccS6XYkuzbL490GXFe/wK5pqJitDaerOzm121EaVGuH7jwC+8rDo+DIrmLvwgCbqKorZ6rGqKM6A0poEqt5vAzoDEnS6U1MGJMARdzVMbTuGjvWz/VAU57X8CyAc6f1AKJWikWMLv6CQfzS3WlgRH7eKyiTenv3wW/A9c4DYerDkweBMZBVWHhl9rdiD8AWRuVYvQa+Qi3Ta0DZfHT/87I/U8IwaKt8gGbTDG1Y6hrW8ouSLU6EMiT8DCIOoXMiV7KCG596O1O5FTrtbKncQLqozMptd6PkXIJYtbgQ3B1nzVWPO6hYRAauPXdxBFokPfYwFG6sZMv1WExqSkcRJkHBJwBYD2mc6eBJfL+nP03nR8COy6I96mPUxNp6nNRJ6Dw645xPD3Q/+MpyGp5cFSTEAfs/gQdVsXgk0fFjsNEFSpaxt9ttyAw1d9QJy+NgJYvLHN3Qz3Rn7126nPR/scbrsVgX9HrCzAj79UEIaM3ZpxlTW5sTpWeup5HA5KPfug/2nopOFkGp+pTdAIT592AFVXJbxmi95K2FAkv3e12zzWscjfXTYMofU6YYU=
  template:
    metadata:
      name: votely-db
      namespace: votely-prod
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: votely-jwt
  namespace: votely-prod
spec:
  encryptedData:
    jwt-secret: AgCm+6T4YDnAxWaL8J91W3+yvE+baVnnYHRjx5GDHSrom4cMF2SwHtSx23GerLJ376s0I9aU6ADcny5NNdpMkqcGsKmr8G63fcLw22HA4tXQQrW0Nb6kFzUzld8EgFJCMs5Qaoq5BE57O57Kf5UAUKGZbt9CekhhXfQpRVTjmkF9uyXtEGQ7kUqhg64+qNtjmXPbYyzO9u+5gGC/t9kkPaY3ZNzAEyccWacj1U3f5BvIp3VE8ujgc0yyd9xjPbUpkBkDfm5R8ZiynIvgF1ujHdvLUo/9yh6171HX3+9SdCXtwVN9nOrYSP06UHWA8CIKVkCExXgr5D/pfIRUtee9z0IG63rnb14Z7Ye/EuCCi1l2I4dJ/Hx1wweFp/we6Amz29VRVtt+pY0SGVnCAHH6O/fCdT5MKjLuKni+42fqE+OxWJfBsd97a6by/FG7oCBEchZHpWWwWeEj9RipUMixTUyciMkRbgmoJ2fnJJUqb+S6IDAW2JBD8Y3OwkECpu9Q22flZDpL5oPxDIPCP94S+Q9spn9ibhI1DTmBj0dnEKMCBtYUeK/GELTX2+HBM/5m4C41vuLNMQvoOREI/NJn2/F4JL23a9o29hLecKM2qJT/EYrPkOI3/1K69XHnMX1S0gm2Q1CEvDt82boeArHbAJfALZ7pU70sToRMWr1QVj7tZxgOhM9exKYvBix5Zws4w13IjaUm35rrMkg+BibhQgSk+Cfjio4Dd3meJfHvAOtpTRe+boIaZ3DCKE3sKLUmpLEVXh3xKIF4hgkTk34iicny
  template:
    metadata:
      name: votely-jwt
      namespace: votely-prod
