---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: votely-db
  namespace: votely-staging
spec:
  encryptedData:
    database: AgDVIkfs376GemFEI48VmOD3hohFlZoH9uGlNuOZ7BQIdgGkHuJM545GkNmE5NIScJuFAOtpp+uSI2RFKggJ2f5XoZq7zvbbFKbpC2mRtcj3SYA7in5QmJV5BhkPOqGxpRkYpwfAeVSAXkvy5u3GajtOYBt6yraKeT0qTU/gov9/LipHinRyxYcvJxbDrYRzqixREHIksHcKePJtXlwhsgzmueD1PJmapU9HTpho5zjQPYImxCOiytnWPdY0NbtHEVrrrcu9Osce6punRpp+O3J6armiTf2D3DOH8ebi94+zN+eCTCntqvcOypPzChZuEGGxgb9aNplsZKxi8OQ5uydW3QaK8EwAFcAshrd5X/qZunG6JBUnDO6cubsg0qEaMAafy1M5huVJOFxxw+nhx88xWUVdEkwMnwtgpFugb7nUIP4VtroDX7BQ1UHULnc6FzN6dGOhddPRN91Ij9TYP1PwHcPsB63D5mqbRFkk9Y9hoMB2MzgzDDTobbEWwAQlY9hIlKFGM/ys50fbEJ+oeWIugO3/9oshGR1wlHgC0YaDKL75HSZ9Dm6+Ulhpj2kSs0fL9tGt9wGy1Dzx9XH97RAG06FhYZ8Y9TQRzuvZq4sBN+NjsBlP2WfyxhpyqoKGZkT+9xREPsMZFgCN2rE/IfBGdx7xIrh+Y2gj3syVbzMa0MiXYeeESazDEtZUzDzhrdLu8bntdBg=
    password: AgCVO2RKvBvjWvrsm44FrBETNnsaaXwMvuMW8/4J59cr0EcFJDvY/+Lvp8d102lj1SNnKZMkGE7dpFE9O1lq5YJp1BcjKAyVAVxCZf2C7gGpWx09/V8w+4l6gpdWGJfDSazhIoFMzF39McxwHsCvjRVe2/EowNuaQGKcnuH4mmlOGVfv/Cf1tW08lJC2YKRWApT0skV9iuUqY/SnPnFYpe6oKqanhW79tre2+cizitVTZ3barizaU33YhvBTrCDsekq2hiLX+Exw5aAcoS2h3bVNX+2qTlGbaDS1QQ/mkfJOyVy3XELxzTrOuZ/x4cAVaHMcArYiEJ5oUPaxdCxpPnjVKfIgzBdmfg9LhgxtEd27ab80RRPwuu/mVAev3h7k/RQckApmwG8cWkUewjrJ/JyNTX/C3ORfpv9rBJNgoG1X8SuVdn0KxGsP48q9mljMBrubNOnDc3plIvE5lkF39E0+K3qrcw51TseGMf8hkYpEOtyYMn8H4FmcVuSKaBW/GGKV5YfUVwVpwDJ2+mE6roMuah53odJ7bzaPPBslRJBsADTBqO3qEo40+GwL5vLInrQ74WUCxyMbvEEkyBWhs4uXvdRL7bYlkUxQ3+1rVBa/IiSZEV34yPoBhFvl55hqNdcQu/tS2tp2X17H9Sc/hI7q9zvSYjOLJJsp2aryqO416VSiqd+BKDYQEeubPoU043XvGTJ13FIvBCIKXXn7i2MXFZ1Q3WSkF4je3Ad66S52Pq/4y0AdvuntS8u9p1NvISE=
    username: AgC9gHYOUiGGMJVmO9f3o8xxwPiJw6FbfPp2ZUDeOwRkiiejcM7/2Ex8NHFB4Gl4ajA90tYxoJilKYjpEZwxVI8PGVrgW0qNydXPzLkjKCj4rHWOQgvR5gKDA3PGPk4nv/4jyhh7fTZLKkDiI5gzs4ZE483Cl2MuL0kgituKGWI41ESPELZsyqPuIKYYwq+oLjKopG6LqdTW9y20eBHHsPwI0GH7ps63BR19aQL6AjhME8uVwyN+hHS2SrrbvclRLp+nog+hzyI8lS5iAZUUzrzQJO725SoZkPXe9iBVR3lfOc7LbJ/ZKDlSqIuHPtJqOJ8r3nbFDQbjGbe4Zsb396rbVmNi/Hdg3xKPBtFWv/AgMp7HQeaM6KDrEXyl/Pwmxo0m6UyxMNdmgFtSZIS6HtQhFh8vls74XEViNOTSPM3CbVlH018oxF/sK9TqXx8viteTdQ2+S+f/1c48DRnwI5Fe9xJiE58yV0gSD77IQC8EwDj1T06w6mrRariiWdnGdwXkaONI1rekJQHQ1TSeiZf9+vTq4tvYBDdKsm3Wb3VjRI2h8TUlmm7OQv8JvC6BnW3qYH0OdBPD54cmAUfgGnUC0DL30xmv2VifzClDc5LXnn+wEaUVtckmkaNck9IpI46QydxQKtzy9MG1BgaEEUjKKPI+sCy53nPXqh7/flVJ1tjibWgbQSjYY9nrRXmvZkI21DMO8uU=
  template:
    metadata:
      name: votely-db
      namespace: votely-staging
---
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: votely-jwt
  namespace: votely-staging
spec:
  encryptedData:
    jwt-secret: AgAVbQNV+LJnaMCZRWb9FMlHRtsBVO5UsfSkhhGKN7H/mW+htJelBtVFc2Fm/NampsICZutQFDsaKHFNFpnNwrA/IsbVn1MJBKYYcvJjXZaE0ovoJvR6W4ZiL25yqHGnyaMHLhdGBZf8vUKfLcv2SbiCiN64rFNXPlTaPcyyGbfvKsAlyHZ0VUILu6AI0n9RtoT8DFhkO5xlivcmDNPMuczf7tyY3290Q2qYl4ARG52CgzOojdX0E3Ld/8iEdZNEESZiu0IRPGjpTRIQhDK1XHFPiJq1I5DSvn7131ZDbH8yobD3J5OGBn/mysAfLeu3/WbDJ551ZuioLnpe8+WlltctETRUbNXEWupxKC6Fuar0DoCCGqWhhmaAuYgKXCgUKZy7aM2RJSSlcHbbsEEkpbQ7i2JFaOeviUv0Pk418ucHr0f4nL/eVkJ48+uetDHUyvdDak3PpF1FRLe1DEHgnIyI6FPTcnbHPGAOEMMvt08y46CSowNIblnjOISZ9DBwXMoOAihlZ5Go7lnWKLauMUnh+Cr+As9FrvmBuFAQL02mf3giQ7En931mfJo0MSLagcWsHR1t6AWakOjfHYn9u/AR+PVzUPJmYByj/eLdqFx9lmOp29XPjz/TnfPrb9cNm+ex6nx9RIpy9zh12GaDyQ/uRZTzhySEpVDkzUOwAJzhdHtp03C4Bm5z6rbrlmW9Lzv6jXLx0cSGL7joImXpWCSSgRmLytXoc2M5avyL7G6LOUQUnV/lwLu04+T5DXmYnf2zmtpueXQ9pNsyUH1bQBZN
  template:
    metadata:
      name: votely-jwt
      namespace: votely-staging
